### PR TITLE
Push multiple images to Docker registry

### PR DESCRIPTION
**Pull request by kwilcox**
Per #47 we can build on different base images. This PR introduces changes to CI to push additional base images to the existing Docker registry.

On push to `main`

* `latest` stays the same
* `latest-jdk8-openjdk` (new) is the same as `latest`
* `latest-jdk11-openjdk` (new) is built with JDK11

On Release:

* `[tag_name]` stays the same
* `[tag_name]-jdk8-openjdk` (new) is the same as `[tag_name]`
* `[tag_name]-jdk11-openjdk` (new) is built with JDK11

@abkfenris @shane-axiom Thoughts? If there is a better way to do this with GH I'm all ears... I don't love the repeated `matrix` and `docker/metadata-action` definitions on each job.

### CODE REVIEW

**Comment by abkfenris** [comment]
While I first went down a rabbit hole exploring how to have the same matrix referenced by multiple workflows, I think with `docker/metadata-action` we can remove the separate release workflow. 

I can try to tinker with it this evening.

**Comment by kwilcox** [comment]
Nice call! I removed the `release` workflow and added some additional tags and conditionals to `push`.

**Comment by abkfenris** [comment]
You may be able to use YAML variables to keep the matrices in sync, or you can have a job output a matrix for others to use.

**Comment by abkfenris** [comment]
Looks like that's a [no for YAML anchors/variables](https://github.community/t/support-for-yaml-anchors/16128).

[Sharing matrix between jobs](https://github.community/t/how-to-share-matrix-between-jobs/128595/11) looks more reasonable.

**Comment by kwilcox** [comment]
hmm that example and some others I found are more verbose and more confusing than just repeating the matrix twice.

**Comment by abkfenris** [comment]
Ya, the DIY way of setting a matrix is a little messy. I've found two actions that may be cleaner:
- https://github.com/marketplace/actions/workflow-matrix
- https://github.com/marketplace/actions/setup-build-matrix

**Review by srstsavage — APPROVED** [review]
I'm a GH actions noob so I can't comment on the nuts and bolts, but the cleanup and image variant publishing are :100: in principle.

**Pull request merged**
