### PR TITLE
Update Docker Hub README on main push or release

### PR DESCRIPTION
**Pull request by srstsavage**
https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
https://github.com/docker/build-push-action/issues/21

🤷

### CODE REVIEW

**Comment by kwilcox** [comment]
so nice!

**Comment by srstsavage** [comment]
~~I botched the vars though, one sec~~

All good I think

**Review by abkfenris — APPROVED** [review]
Oh, that's cool.

**Comment by srstsavage** [comment]
Nice, works.

https://hub.docker.com/r/axiom/docker-erddap

Note that the Docker Hub personal access token needs read/write/delete scope for some reason, not just read/write.

**Pull request merged**
