### PR TITLE
Remove .hdf and .nc files from range request exclusion

### PR DESCRIPTION
**Pull request by tjcrone**
This removes the .hdf and .nc extensions from the <extensionsNoRangeRequests> section of messages.xml.

### CODE REVIEW

**Comment by rsignell-usgs** [comment]
Thanks @tjcrone!    

When this is merged and deployed on the OOI ERDDAP server hopefully this `curl` command:
```
curl -I https://erddap.dataexplorer.oceanobservatories.org/erddap/files/ooi-rs03ashs-mj03b-09-botpta304/station_104304_split_20200101-20210101.nc 
```
will return:
```
Accept-Ranges: bytes
```

**Comment by tjcrone** [comment]
Yeah I have tested this during the Docker build but @rsignell-usgs and I have not had a chance yet to test the effect on the server stack. This should be tested in context. Also, this method of deletion should be fine as long as we do not expect the source file to change. But if there is a chance of that we should consider making edits to these files with a proper XML parser.

**Comment by rsignell-usgs** [comment]
@abkfenris built and pushed the container and I tried it out on our ERDDAP at https://geoport.usgs.esipfed.org/erddap.

It works:
https://nbviewer.org/gist/rsignell-usgs/e40dc3f7ea8631f3f73d83223f57b015

Need to find some bigger files to try on with kerchunk of course -- this one is tiny -- just 1mb.




```

**Comment by tjcrone** [comment]
Fantastic @rsignell-usgs! Thank you for testing in context with your ERDDAP. I'm assuming that you tried the curl command and got `Accept-Ranges: bytes`? Really appreciate you taking time to help with this.

**Comment by rsignell-usgs** [comment]
@tjcrone , yes:
```
curl -I https://geoport.usgs.esipfed.org/erddap/files/9171eco-a/9171eco-a.nc
```
returns:

HTTP/1.1 200 
Server: nginx/1.18.0
Date: Mon, 08 Nov 2021 20:50:30 GMT
Content-Type: application/x-netcdf
Content-Length: 1395594
Connection: keep-alive
Strict-Transport-Security: max-age=0
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Content-Disposition: attachment;filename=9171eco-a.nc
Content-Encoding: identity
**Accept-ranges: bytes**

**Comment by rsignell-usgs** [comment]
@shane-axiom, it would be great to merge this and deploy on the ooi erddap.   
I happen to know @kwilcox is not available currently.  🏖️  + 🌴 +  🏊 + 🍹

**Comment by srstsavage** [comment]
@rsignell-usgs "deploy on the ooi erddap" is non-trivial (complex federated setup, multi-hour load times, etc). Can we start with a test deployment containing a small subset of the OOI data to play with? Any instrument you're particularly interested in?

**Comment by tjcrone** [comment]
@shane-axiom thank you for helping with this. I am working with a student on the BOTPT dataset. Perhaps we can try these files for our tests?

https://erddap.dataexplorer.oceanobservatories.org/erddap/files/ooi-rs03ccal-mj03f-05-botpta301/

**Comment by kwilcox** [comment]
I'd like to get this capability into the 2.18 container release so it can be propagated up to OOI soon.

This would change how the container functions as compared to a default ERDDAP install, which we are trying to avoid. Did anyone ping Bob if this can be made into a configuration option in `setup.xml` in the future? Then it can be controlled via ENV variable, rather than enabled for all ERDDAP installs running this container. In the meantime I don't mind changing the default `setenv.sh` from this project and making the changes to `messages.xml` if an env variable is set: `ERDDAP_enableNetcdfByteRangeRequests`.

**Comment by abkfenris** [comment]
I believe that Bob was worried about this change on two fronts. 
- That ERDDAP may not be the most efficient general file store and isn't optimized for serving read requests (it might still have to read the whole file per request).
- As is, I don't think this change differentiates between allowing range requests for `/files/` access, but not `/griddap/` or `/tabledap/` which definately add a ton of overhead and potentially variable byte alignment between requests due to having to re-process each request cycle.

**Comment by rsignell-usgs** [comment]
@kwilcox, your idea sounded good to me:  
>  In the meantime I don't mind changing the default setenv.sh from this project and making the changes to messages.xml if an env variable is set: `ERDDAP_enableNetcdfByteRangeRequests`.

Why closed instead of enabling this approach?     Seems like this functionality could be even more useful now that we have [kerchunk](https://fsspec.github.io/kerchunk/).

**Comment by kwilcox** [comment]
This was inadvertently closed when moving the default branch to "main".

Are you planning to submit changes to this PR to enable the changes only when an environmental variable is set?

**Comment by rsignell-usgs** [comment]
No, but I was hoping you were.  :)

**Comment by kwilcox** [comment]
This is possible since https://github.com/axiom-data-science/docker-erddap/pull/51 was merged by mounting an init script. I'll cut a release as soon as other outstanding PRs are merged. You can build this container from the `main` branch in the meantime!

**Comment by rsignell-usgs** [comment]
Awesome.  Thanks @kwilcox !

**Pull request closed without merging**
